services:
  jatos:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jatos.rule=Host(`${JATOS_DOMAIN}`)"
      - "traefik.http.routers.jatos.entrypoints=websecure"
      - "traefik.http.routers.jatos.tls=true"
      - "traefik.http.services.jatos.loadbalancer.server.port=9000"

  traefik:
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./certs:/certs:ro"
      - "./dynamic:/etc/traefik/dynamic:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
